### ISSUE TITLE
Running the repo locally

### ISSUE THREAD

**Issue by farhangnaderi** [markusbuchholz/stonefish_ros2_marine_robotics#1]
Hey, 

Thanks for making this possible. I am trying to run this locally and the issue I do  not understand is why ardusim patch is listening to udp 9002 which is gazebo although we are running Stonefish? 

This makes ardusim patch to loop through the nonexistent port to get gps, imu and odom data.

Anything I might be missing? 

Thanks,

**Comment by markusbuchholz** [comment]
Hei @farhangnaderi,

Thanks for our checks and comments.

I am sorry that something is not working.

I reached the repo and reran the scripts I pulled. I have not experienced any issues.

Have you followed all the instructions in the sequence I included?

I added extra script which extracts all position information from Ardupilot ```position_data.py```.

Check again following sequences,

```bash
#terminal 1
ros2 run stonefish_bluerov2 ardusim_patch.py

#terminal 2
ros2 launch cola2_stonefish bluerov_fls_simulation.launch.py

#terminal 3
sim_vehicle.py -v ArduSub -f vectored_6dof --model JSON --map  -l 55.99541530863445,-3.3010225004910683,0,0 -m --streamrate=-1

#terminal 4
cd /home/sf_ws/src/extras_rov
python3 position_data.py
```

**Comment by markusbuchholz** [comment]
I closed the issue as I provided feedback to run it correctly.

**Comment by farhangnaderi** [comment]
> I closed the issue as I provided feedback to run it correctly.

Thanks Markus. I will give it a try again.
